name: TheBridgeLCP
version: '${project.version}'
main: org.lordalex.thebridgelcp.TheBridgeLCP
softdepend: [ ProtocolLib ]
commands:
  game:
    description: "start interrupt finish flag"
  tb:
    description: "stats spectoteam teamname"