name: TheBridgeLCP
version: '1.0-SNAPSHOT'
main: org.lordalex.thebridgelcp.TheBridgeLCP
softdepend: [ ProtocolLib ]
commands:
  game:
    description: "start interrupt finish flag"
  tb:
    description: "stats spectoteam teamname"